pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=scala-steward"
      - "status-success=Travis CI - Pull Request"
    actions:
      merge:
        method: merge
